package com.tweetappdynamodb.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonFormat;

@DynamoDBTable(tableName = "tweet")
public class Tweet {
	@DynamoDBHashKey  (attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String id;
	@DynamoDBAttribute
	public String userid;
	@DynamoDBAttribute
	public String tweet;
	@DynamoDBAttribute
	@JsonFormat(pattern="yyyy-MM-dd hh:mm:ss")
	public Date date;
	@DynamoDBAttribute
	public List<String> reply=new ArrayList();
	@DynamoDBAttribute
	public String firstname;
	@DynamoDBAttribute
	public int likes;
	public Tweet() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	

	public String getId() {
		return id;
	}



	public void setId(String id) {
		this.id = id;
	}



	public String getUserid() {
		return userid;
	}



	public void setUserid(String userid) {
		this.userid = userid;
	}



	public String getTweet() {
		return tweet;
	}



	public void setTweet(String tweet) {
		this.tweet = tweet;
	}



	public Date getDate() {
		return date;
	}



	public void setDate(Date date) {
		this.date = date;
	}



	public List<String> getReply() {
		return reply;
	}



	public void setReply(List<String> reply) {
		this.reply = reply;
	}



	public String getFirstname() {
		return firstname;
	}



	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}



	public int getLikes() {
		return likes;
	}



	public void setLikes(int likes) {
		this.likes = likes;
	}



	public Tweet(String id, String userid, String tweet, Date date, List<String> reply, String firstname, int likes) {
		super();
		this.id = id;
		this.userid = userid;
		this.tweet = tweet;
		this.date = date;
		this.reply = reply;
		this.firstname = firstname;
		this.likes = likes;
	}



	@Override
	public String toString() {
		return "Tweet [id=" + id + ", userid=" + userid + ", tweet=" + tweet + ", date=" + date + ", reply=" + reply
				+ ", firstname=" + firstname + ", likes=" + likes + "]";
	}
	
}
